name: 'Create raw file'
description: 'Create a file with raw data'
branding:
  icon: file-plus
  color: green
inputs:
  file-name:
    description: 'The name of the file to create'
    required: true
    default: '.env'
  file-data:
    description: 'The data to write to the file'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file-name }}
    - ${{ inputs.file-data }}
